# Generated by Django 3.2.10 on 2022-07-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebasHTTP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
